### ISSUE TITLE
In version 0.11 of spin there is not included endian check

### ISSUE THREAD

**Issue by BKPepe** [SIDN/sidn_openwrt_pkgs#12]
Spin can not be compiled for now. This happens since https://github.com/SIDN/sidn_openwrt_pkgs/commit/649074fabe7d7775eb02401a161b8edd9995bcef.

It fails with following output:
`install: cannot stat '/build/build_dir/target-arm_cortex-a9+vfpv3_musl_eabi/spin-0.11/src/tools/endian-check/endian-check': No such file or directory`

I see that in [master branch of spin](https://github.com/SIDN/spin/tree/master/src/tools), there is present endian-check, but in released versions, it is not.

Proposed solutions:
1. Release a new version of spin, where is included endian-check or use the latest commit from the master branch
2. Revert the commit.

**Comment by tjeb** [comment]
Actually, IMO the correct fix is a different one; the master branch of the packages feed should point to the master branch of the package sources.

Tagged releases (such as 9474f21d) do point to the correct release tar.gz files.

I have updated this in e8d1110e, so it should pull and build the latest sources now.

**Comment by BKPepe** [comment]
I'm thinking why did you want to use your solution instead of two provided, which are acceptable? Let me tell you what's wrong with your solution.

The most important thing, which I see is that each time, you do change (which you did!) the package is created with a name: spin_0.11-1_arm_cortex-a9_vfpv3.ipk

This means that if anyone had installed spin with version 0.11-1 that it does not have the latest changes and if anyone installs it now that these two packages differ! The router is not aware that there is a new version, because the versioning is the same. This is hard for debugging and looking at it.

The other thing, you don't want to build master branches with each commit. You want to provide users stable releases of your package instead of daily builds. 

For me, it sounds to be similar to [OpenWrt snapshots](https://openwrt.org/releases/snapshot). Automatic daily builds, which are not tested and you don't check what someone pushes if it does break something related to your package as you don't have control for it and when it happens, did you notice it?  I understand that you have commit rights and you can revert it very easily, but did you know what others are pushing to it? For example, if you don't have them. You can do it for your own builds if you have time, but don't do it for others.

I would point out a few things about it, but these two are the most important.

**Comment by tjeb** [comment]
Right, after some internal discussion we have decided to make the policy to have the master branch point to the latest release (in essence revert the patch causing this issue), and have a separate branch for snapshot builds.

Just a bit of additional explanation, since you were wondering why the two solutions weren't fully acceptable: I was originally under the impression that is was customary to use the feeds.conf branch/commit support (i.e. always use ^ or ; when using src-git) in order to build stable packages for end-users, so that the master could be used for bleeding-edge snapshot builds, so I did not think end-users would end up with packages build from master. With that in mind, the reasoning was threefold:
- the current master for spin isn't ready for release yet
- we do want a way to build the latest snapshot, i.e. the lastest master, for our testers and other developers
- the way we used to do it (rewrite about parts of the Makefile on the fly) was masking problems such as the one you reported (mismatchs between latest release and master in terms of what to build and install)

You point about versioning was of course correct, but since I did not think end-users would be running master builds, this did not seem to be much of a problem.

Either way, master is now safely pointing to the latest full release, so thank you for the report, and enjoy :)
